### ISSUE TITLE
Rate limiting protection

### ISSUE THREAD

**Issue by viveret** [pink-umbrella/pink-umbrella#10]
Is there a library that can do this or do we need to write our own protection service?

EDIT: No longer focusing on DDOS protection since P2P applications are harder to DDOS

**Comment by sainteos** [comment]
I found this, haven't looked at the details  to much though https://github.com/AltraMayor/gatekeeper

**Comment by viveret** [comment]
Relevant paper: https://link.springer.com/chapter/10.1007/978-3-540-69295-9_3

**Comment by viveret** [comment]
P2P networks make DDoS attacks uneconomical: https://zovolt.com/mitigate-ddos-attacks-with-p2p/
I think we could keep this on the back-burner unless something changes and this needs higher priority.

Rate limiting will be something to keep track of so that bad nodes don't abuse the system

**Comment by viveret** [comment]
From tumblr: 
These rate limits include:
-    300 API calls per minute, per IP address.
-    18,000 API calls per hour, per IP address.
-    432,000 API calls per day, per IP address.
-    1,000 API calls per hour, per consumer key.
-    5,000 API calls per day, per consumer key.
-    250 new posts (including reblogs) per day, per user.
-    150 images uploaded per day, per user.
-    200 follows per day, per user.
-    1,000 likes per day, per user.
-    10 new blogs per day, per user.
-    10 videos uploaded per day, per user.
-    5 minutes of total video uploaded per day, per user.

Note that these rate limits are based on the Tumblr servers' internal clocks and that the daily limits are per calendar day.

There are also overall limits to a few specific actions, including:
-    A blog can only follow 5,000 other blogs at a time.
-    A blog can only have 300 queued posts at a time.
-    You can only filter up to 1,000 tags at a time.

**Comment by viveret** [comment]
Completed (very roughly) by #08bb026
