### ISSUE TITLE
API for integrations

### ISSUE THREAD

**Issue by viveret** [pink-umbrella/pink-umbrella#13]
Need to generate private keys per application and user or for server instance and grant explicit permissions. We could pass credentials via HTTP headers to piggy-back off of existing technologies. Sensitive fields and data should be encrypted with a message cipher.

JavaScript example:
`// Request with custom header
$.ajax({
    url: '<url>',
    headers: { '<x-my-custom-header>': '<some value>' }
});
`

**Comment by viveret** [comment]
Completed in f193ec2 , use `X-Api-Key` with public key to access API routes. Body data is automatically decrypted and verified with the client's public key. Add api keys by going to /admin/integrations

**Comment by viveret** [comment]
@sainteos if you need help with integration authentication I can explain more in a Wiki page documenting it, I'll be creating another repo for a client console app that can demonstrate how to create integrations.

**Comment by sainteos** [comment]
> @sainteos if you need help with integration authentication I can explain more in a Wiki page documenting it, I'll be creating another repo for a client console app that can demonstrate how to create integrations.

That would be great

**Comment by viveret** [comment]
@sainteos updated with auto-generated docs for the API and a lot of the data models. Still need to fully document everything but its a start. I also added a footer icon to go to the docs. See #27 . The client console app will be next.
