### ISSUE TITLE
Unsupported filetype

### ISSUE THREAD

**Issue by sainteos** [pink-umbrella/pink-umbrella#2]
In the Media Upload view, I have tried to upload .png, .jpg, and .mov. For the first two, I just get an error that says "Unsupported file type." For a .mov, I get the "The connection was reset" page.

**Comment by viveret** [comment]
I didn't update the running instance when this was logged, could you try this again and see if it still does not support png or jpg? That's all it supports right now.

**Comment by viveret** [comment]
Fixed b887211
