### ISSUE TITLE
P2P support

### ISSUE THREAD

**Issue by viveret** [pink-umbrella/pink-umbrella#24]
https://gnunet.org/en/
https://github.com/SyncfusionSuccinctlyE-Books/The-Kademlia-Protocol-Succinctly

**Comment by sainteos** [comment]
Ooh, someone showed this to me today: https://github.com/perlin-network/noise

**Comment by viveret** [comment]
That looks like a good way to connect peers - we would need to just keep track of peer information, which isn't too difficult.

**Comment by sainteos** [comment]
So, noise looks cool, I've never used go before. The syntax turned me off at first, but the more I read it, I'm kinda starting to get used to it. Have you had any go projects? 

I think I may try to build a light elixir P2P framework (that doesn't necessarily have to be the one we use), because a lot of things that noise does are features at the language/VM level (and is concurrent, and scalable by design). Then I could find packages for the specific features like, for Curve25519, AES 256-bit GCM, discovery, and then the actual data transfer scheme, whether it's Phoenix channels, or MQTT or, something else. 

I think there's a space for that in the elixir universe, but like I said, doesn't have to be what we use.

**Comment by viveret** [comment]
@sainteos I like GO, it has its pros and cons. I haven't actually used it though, so I'd need to learn more about it. If you could build a P2P layer then that would be awesome, since that language / framework might have an advantage to rewriting a lot of that in C#. We can also abstract the P2P layer so that other users can integrate different P2P providers.

**Comment by viveret** [comment]
@sainteos the P2P layer mostly just needs to worry about peer and user information, along with encryption information. Most of this can be read over a JSON or REST API that we can develop together.

**Comment by viveret** [comment]
@sainteos have you had a chance to work on an Elixir P2P framework? I just updated the repo to use Elastic search for synchronizing peers and local data into a queryable database, but I think having the traffic go over the P2P framework would be better than the current HTTPS REST method.

**Comment by viveret** [comment]
@sainteos I tried making a layer for P2P connections and HTTP request forwarding but I'm not sure perlin-network will work since when data is sent, the connection back to the requestee is lost, so a response cannot be sent back without more work than what I think is necessary to build out P2P / discovery. I think we should emulate perlin-noise in its API and simplicity to connect to peers.

**Comment by viveret** [comment]
package main

import (
	"io/ioutil"
//	"net"
	"net/http"
	"net/url"
	"fmt"
	"bytes"
	"bufio"
	"log"
    "github.com/perlin-network/noise"
	"github.com/perlin-network/noise/kademlia"
	"go.uber.org/zap"
	"os"
	"os/signal"
	"strings"
	"context"
	"time"
    "strconv"
)

// printedLength is the total prefix length of a public key associated to a chat users ID.
const printedLength = 8

func help(node *noise.Node) {
	fmt.Printf("Your ID is %s(%s)\n",
		node.ID().Address,
		node.ID().ID.String()[:printedLength],
	)
}


// peers prints out all peers we are already aware of.
func peers(overlay *kademlia.Protocol) {
	ids := overlay.Table().Peers()

	var str []string
	for _, id := range ids {
		str = append(str, fmt.Sprintf("%s(%s)", id.Address, id.ID.String()[:printedLength]))
	}

	fmt.Printf("You know %d peer(s): [%v]\n", len(ids), strings.Join(str, ", "))
}

// discover uses Kademlia to discover new peers from nodes we already are aware of.
func discover(overlay *kademlia.Protocol) {
	ids := overlay.Discover()

	var str []string
	for _, id := range ids {
		str = append(str, fmt.Sprintf("%s(%s)", id.Address, id.ID.String()[:printedLength]))
	}

	if len(ids) > 0 {
		fmt.Printf("Discovered %d peer(s): [%v]\n", len(ids), strings.Join(str, ", "))
	} else {
		fmt.Printf("Did not discover any peers.\n")
	}
}

// bootstrap pings and dials an array of network addresses which we may interact with and  discover peers from.
func bootstrap(node *noise.Node, addresses ...string) {
	for _, addr := range addresses {
		ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
		_, err := node.Ping(ctx, addr)
		cancel()

		if err != nil {
			fmt.Printf("Failed to ping bootstrap node (%s). Skipping... [error: %s]\n", addr, err)
			continue
		}
	}
}

//
// func listenForOutgoingTraffic(hostNode *noise.Node, hostPort int, destPort int) {
// 	// Listen for incoming connections.
//     l, err := net.Listen("tcp", "localhost:" + string(destPort))
//     if err != nil {
//         fmt.Println("Error listening:", err.Error())
//         os.Exit(1)
//     }
	
// 	// Close the listener when the application closes.
// 	defer l.Close()
	
//     for {
//         // Listen for an incoming connection.
//         conn, err := l.Accept()
//         if err != nil {
//             fmt.Println("Error accepting: ", err.Error())
//             os.Exit(1)
//         }
//         // Handle connections in a new goroutine.
//         go handleOutgoingRequest(hostNode, hostPort, conn)
//     }
// }

// handleOutgoingRequest
// func handleOutgoingRequest(hostNode *noise.Node, hostPort int, conn net.Conn) {
// 	defer conn.Close()
// 	reqData, err := ioutil.ReadAll(conn)
// 	if err != nil {
// 		log.Fatal(err)
// 	}
// 	req, err := http.ReadRequest(bufio.NewReaderSize(bytes.NewReader(reqData), 1024))
// 	if err != nil {
// 		log.Fatal(err)
// 	}

// 	reqDestination := req.Header["Peer-Destination"][0]
// 	reqDestinationType := req.Header["Peer-Destination-Type"][0]

// 	switch (reqDestinationType) {
// 	// case "id":
// 	// 	reqNode, err := hostNode.Ping(context.TODO(), reqDestination)
// 	// 	break;
// 	case "address":
// 		err = hostNode.Send(context.TODO(), reqDestination, reqData)
// 		break;
// 	default:
// 		log.Fatal("Invalid destination type: " + reqDestinationType)
// 		break;
// 	}
// 	if err != nil {
// 		log.Fatal(err)
// 	}

// 	// responseData, err := ioutil.ReadAll(conn)
// 	// if err != nil {
// 	// 	log.Fatal(err)
// 	// }
// }

// This example demonstrates how to send/handle RPC requests across peers, how to listen for incoming
// peers, how to check if a message received is a request or not, how to reply to a RPC request, and
// how to cleanup node instances after you are done using them.
func main() {
	listenPort, err := strconv.ParseInt(os.Args[1], 10, 64) // 9000
	if err != nil {
		panic(err)
	}

	hostPort, err := strconv.ParseInt(os.Args[2], 10, 64) // 12524
	if err != nil {
		panic(err)
	}

	logger, err := zap.NewDevelopment(zap.AddStacktrace(zap.PanicLevel))
	if err != nil {
		panic(err)
	}
	defer logger.Sync()

	node, err := noise.NewNode(noise.WithNodeLogger(logger), noise.WithNodeBindPort(uint16(listenPort)))
	if err != nil {
		panic(err)
	}
	defer node.Close()

	// Forward HTTP requests to local host
	node.Handle(func(ctx noise.HandlerContext) error {
		req, err := http.ReadRequest(bufio.NewReaderSize(bytes.NewReader(ctx.Data()), 1024))
		if err != nil {
			log.Fatal(err)
		}
		reqUrl := "http://localhost:" + string(hostPort) + "/Api/Peer/Msg?url=" + url.QueryEscape(req.URL.String())
		switch (req.Method) {
		case "Post":
			resp, err := http.Post(reqUrl, req.Header["Content-Type"][0], req.Body)
			if err != nil {
				log.Fatal(err)
			}
			data, err := ioutil.ReadAll(resp.Body)
			resp.Body.Close()
			if err != nil {
				log.Fatal(err)
			}
			ctx.Send(data)
			break;
		}
		return nil
	})

	// Instantiate Kademlia.
	events := kademlia.Events{
		OnPeerAdmitted: func(id noise.ID) {
			fmt.Printf("Learned about a new peer %s(%s).\n", id.Address, id.ID.String()[:printedLength])
		},
		OnPeerEvicted: func(id noise.ID) {
			fmt.Printf("Forgotten a peer %s(%s).\n", id.Address, id.ID.String()[:printedLength])
		},
	}

	overlay := kademlia.New(kademlia.WithProtocolEvents(events))

	node.Bind(overlay.Protocol())

	if err := node.Listen(); err != nil {
		panic(err)
	}

	help(node)

	node.Ping(context.TODO(), "localhost:8000")

	c := make(chan os.Signal, 1)
	signal.Notify(c, os.Interrupt)
	<-c
}

**Comment by viveret** [comment]
@sainteos from https://docs.gnunet.org/handbook/gnunet.html#Introduction :
> GNUnet in its current version is the result of almost 20 years of work from many contributors. So far, most contributions were made by volunteers or people paid to do fundamental research. At this stage, GNUnet remains an experimental system where significant parts of the software lack a reasonable degree of professionalism in its implementation. Furthermore, we are aware of a significant number of existing bugs and critical design flaws, as some unfortunate early design decisions remain to be rectified. There are still known open problems; GNUnet remains an active research project.

> GNUnet is not merely a technical project, but also a political mission: like the GNU project as a whole, we are writing software to achieve political goals with a focus on the human right of informational self-determination. Putting users in control of their computing has been the core driver of the GNU project. With GNUnet we are focusing on informational self-determination for collaborative computing and communication over networks. 

I think gnunet is off the table, which is a bummer. Let's also take note of those lessons learned.

**Comment by viveret** [comment]
https://github.com/pink-umbrella/pink-umbrella/issues/18 will continue the conversation around P2P traffic
