### ISSUE TITLE
Blockchain

### ISSUE THREAD

**Issue by viveret** [pink-umbrella/pink-umbrella#32]
https://github.com/danielgerlag/NBlockchain

**Comment by sainteos** [comment]
Oh, heh, I just saw this.

**Comment by sainteos** [comment]
[CovenantSQL](https://developers.covenantsql.io/docs/en/intro) is something I found earlier too. Decentralized blockchain SQL

**Comment by viveret** [comment]
@sainteos I think blockchain is primarily used for proof of work, but for this system we don't require proof of work for transactions to be made. We just require correct credentials. I think the idea of distributed hashes of documents is the idea initially presented in this issue, but is being handled in #18 so I will close this

**Comment by sainteos** [comment]
Yeah, later in the game, if we are dealing with genuine transactions, like actually tracking voting, bureaucracy, and other things like that, the need for transparent proof of work to build essentially a living document like a constitution or something, I think blockchain will come back into play.
