### ISSUE TITLE
Getting a 503 response

### ISSUE THREAD

**Issue by sainteos** [pink-umbrella/pink-umbrella#43]
The dev instance of pink-umbrella is coming up 503 unavailable when I request the home address

**Comment by viveret** [comment]
Took it offline for now until V1 is up. If you need access just reply back on this issue and I can add your IP(s) to an allowed list so that you can still access it

**Comment by sainteos** [comment]
Ahh cool, good to know. I'll stand it up local then (adding my IP would be hard because it changes frequently)
