### ISSUE TITLE
Upload Media Internal Server Error

### ISSUE THREAD

**Issue by sainteos** [pink-umbrella/pink-umbrella#5]
I tried uploading a pic and was met with an Internal Server Error saying DirectoryNotFoundException.
Here's the stacktrace:
<img width="1269" alt="Screen Shot 2020-06-20 at 13 33 36" src="https://user-images.githubusercontent.com/13241909/85211111-a7806880-b2fa-11ea-84c7-3fc1bffbe105.png">

**Comment by viveret** [comment]
Oh yeah need to add a line to create the directory if it does not exist

**Comment by viveret** [comment]
Fixed by e842d84
