### ISSUE TITLE
Add a field for "attributed to" on media items

### ISSUE THREAD

**Issue by sainteos** [pink-umbrella/pink-umbrella#6]
I think it would be good/useful to attribute media items to their sources. That way we don't have to be wary of pulling media in? I'm just wondering if it's a good idea just to give credit but also so we can pull media from anywhere, just in case it comes from a source that isn't part of pink-umbrella yet?

**Comment by viveret** [comment]
We can add a `credit` string field that lets a user input a text description of the credit or a URL to an original source.

**Comment by viveret** [comment]
Fixed by 7b94649
