### ISSUE TITLE
Tags should be added on something other than whitespace

### ISSUE THREAD

**Issue by sainteos** [pink-umbrella/pink-umbrella#8]
So, with the preloaded tags that have spaces in them, the tags with spaces in them work fine. If I try to add another tag along the same scheme of "test tag 5" it ends up putting those as 3 different tags. Perhaps we should be adding tags on commas or double space or semi colon?
<img width="878" alt="Screen Shot 2020-06-20 at 13 51 18" src="https://user-images.githubusercontent.com/13241909/85211379-705f8680-b2fd-11ea-9ce2-2fb72ad893c2.png">

**Comment by viveret** [comment]
The tags have to break on `[^a-z0-9_]` so that it can be regexed from text posts, so the test tags should not have spaces, nor should it be allowed to create a tag with invalid characters.

**Comment by viveret** [comment]
Fixed with 8039ded
